version: '3.8'

services:
    # Nodo 1 de la base de datos: El inicializador del clúster galera
    db-node1:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_DATABASE: db_appvotaciones
            MARIADB_USER: user_appvotaciones
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_PASSWORD_FILE: /run/secrets/db_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            # Cambiar a 'no' una vez haya arrancado todo
            MARIADB_GALERA_CLUSTER_BOOTSTRAP: 'yes'
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - db_password
            - galera_sync_password
        volumes:
            - db_data_1:/bitnami/mariadb
            - ./database/02_esquema_db.sql:/docker-entrypoint-initdb.d/02_esquema_db.sql:ro
        networks:
            - votacion_net
        deploy:
            replicas: 0 # El script encender_db.sh se encarga de crear la replica necesaria
            endpoint_mode: dnsrr # Desactiva el VIP de Swarm para este servicio
            placement:
                constraints:
                    - node.labels.role == database

    # Nodo 2 de la base de datos
    db-node2:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - galera_sync_password
        volumes:
            - db_data_2:/bitnami/mariadb
        networks:
            - votacion_net
        deploy:
            replicas: 0 # El script encender_db.sh se encarga de crear la replica necesaria
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.hostname == servidor-worker1

    # Nodo 3 de la base de datos
    db-node3:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - galera_sync_password
        volumes:
            - db_data_3:/bitnami/mariadb
        networks:
            - votacion_net
        deploy:
            replicas: 0 # El script encender_db.sh se encarga de crear la replica necesaria
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.hostname == servidor-worker2

    db-proxy:
        image: haproxy:lts
        volumes:
            - ./infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - '8404:8404' # Panel de estadísticas
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager # Mejor que el proxy esté en el manager para control centralizado

    backend:
        image: 192.168.50.1:5000/votacion-backend:latest
        ports:
            - '8000:80'
        environment:
            DB_HOST: db-proxy
            DB_NAME: db_appvotaciones
            DB_USER: user_appvotaciones
        secrets:
            - db_password
            - jwt_secret
        networks:
            - votacion_net
        deploy:
            replicas: 2 # 2 instancias del backend
            placement:
                constraints:
                    - node.labels.role == app

    frontend:
        image: 192.168.50.1:5000/votacion-frontend:latest
        ports:
            - '3000:3000'
        networks:
            - votacion_net
        deploy:
            replicas: 2 # 2 instancias del frontend
            placement:
                constraints:
                    - node.labels.role == app

    phpmyadmin:
        image: phpmyadmin:5.2-apache
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db-proxy
            PMA_USER: user_appvotaciones
            PMA_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
        networks:
            - votacion_net
        deploy:
            # phpmyadmin puede ir a cualquier nodo de app
            placement:
                constraints:
                    - node.labels.role == app

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3001:3000'
        environment:
            # Cambiar tras el arranque
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - grafana_data:/var/lib/grafana
            - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager

    node-exporter:
        image: prom/node-exporter:latest
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
        networks:
            - votacion_net
        deploy:
            mode: global

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - votacion_net
        deploy:
            mode: global

secrets:
    db_root_password:
        external: true
    db_password:
        external: true
    galera_sync_password:
        external: true
    jwt_secret:
        external: true

networks:
    votacion_net:
        driver: overlay # Red especial de Swarm para que los nodos se comuniquen

volumes:
    db_data_1:
    db_data_2:
    db_data_3:
    prometheus_data:
    grafana_data:
