version: '3.8'

services:
    # Nodo 1 de la base de datos: El inicializador del clúster galera
    db-node1:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_DATABASE: db_appvotaciones
            MARIADB_USER: user_appvotaciones
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_PASSWORD_FILE: /run/secrets/db_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            # Cambiar a 'no' una vez haya arrancado todo
            MARIADB_GALERA_CLUSTER_BOOTSTRAP: 'yes'
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - db_password
            - galera_sync_password
        volumes:
            - db_data_1:/bitnami/mariadb
        configs:
            - source: esquema_sql
              target: /docker-entrypoint-initdb.d/1_esquema_db.sql
            - source: mock_data_sql
              target: /docker-entrypoint-initdb.d/2_mock_data.sql
        networks:
            - votacion_net
        deploy:
            replicas: 0 # TARGET_NODO_GALERA
            endpoint_mode: dnsrr # Desactiva el VIP de Swarm para este servicio
            placement:
                constraints:
                    - node.labels.role == database
            resources:
                reservations:
                    cpus: '0.50' # Garantiza al menos la mitad de un núcleo
                    memory: 512M # Garantiza al menos 512 MB de RAM
                limits:
                    cpus: '1.40' # Máximo 70% de los núcleos de la maquina
                    memory: 1536M # Máximo 3 cuartos de la RAM de la máquina

    # Nodo 2 de la base de datos
    db-node2:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - galera_sync_password
        volumes:
            - db_data_2:/bitnami/mariadb
        networks:
            - votacion_net
        deploy:
            replicas: 0 # TARGET_NODO_GALERA
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.hostname == servidor-worker1
            resources:
                # Menos recursos ya que no son el nodo principal y hay mas servicios aparte en estas máquinas
                reservations:
                    cpus: '0.25'
                    memory: 384M
                limits:
                    cpus: '0.80'
                    memory: 512M

    # Nodo 3 de la base de datos
    db-node3:
        image: public.ecr.aws/bitnami/mariadb-galera:latest
        command:
            - /opt/bitnami/scripts/mariadb-galera/run.sh
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_es_0900_ai_ci
            - --skip-character-set-client-handshake
        environment:
            MARIADB_GALERA_CLUSTER_NAME: votacion_db_cluster
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_GALERA_MARIABACKUP_USER: galera_sync_user_appvotaciones
            MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/galera_sync_password
            MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://db-node1,db-node2,db-node3
        secrets:
            - db_root_password
            - galera_sync_password
        volumes:
            - db_data_3:/bitnami/mariadb
        networks:
            - votacion_net
        deploy:
            replicas: 0 # TARGET_NODO_GALERA
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.hostname == servidor-worker2
            resources:
                reservations:
                    cpus: '0.25'
                    memory: 384M
                limits:
                    cpus: '0.80'
                    memory: 512M

    db-proxy:
        image: haproxy:lts
        volumes:
            - ./infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - '8404:8404' # Panel de estadísticas
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager # Mejor que el proxy esté en el manager para control centralizado
            restart_policy:
                condition: any # Reinicia siempre que se caiga
                delay: 5s # Espera 5 segundos antes de intentar levantarlo
                max_attempts: 3 # Si falla 3 veces seguidas, desiste (para evitar bucles infinitos)
                window: 120s # Tiempo que debe estar funcionando para considerar el reinicio "exitoso"
            resources:
                # No necesita casi nada ya que es solo para el trafico entre nodos de BD
                reservations:
                    cpus: '0.10'
                    memory: 64M
                limits:
                    cpus: '0.40'
                    memory: 128M

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./infra/nginx/sistema-votacion:/etc/nginx/conf.d/default.conf:ro
        deploy:
            placement:
                constraints:
                    - node.role == manager 
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                # Algo más que HAProxy ya que por aquí pasa todo el trafico de la app
                reservations:
                    cpus: '0.10'
                    memory: 64M
                limits:
                    cpus: '0.50'
                    memory: 256M

    backend:
        image: 192.168.50.1:5000/votacion-backend:latest # php:8.5-apache
        environment:
            DB_HOST: db-proxy
            DB_NAME: db_appvotaciones
            DB_USER: user_appvotaciones
        secrets:
            - db_password
            - jwt_secret
            - dni_pepper
            - blockchain_secret
        networks:
            - votacion_net
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.labels.role == app
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 60s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 256M
                limits:
                    cpus: '0.8'
                    memory: 512M

    frontend:
        image: 192.168.50.1:5000/votacion-frontend:latest # node:24-bookworm-slim
        networks:
            - votacion_net
        deploy:
            replicas: 2 # 2 instancias del frontend
            placement:
                constraints:
                    - node.labels.role == app
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 30s
            resources:
                reservations:
                    cpus: '0.10'
                    memory: 128M
                limits:
                    cpus: '0.8'
                    memory: 512M

    phpmyadmin:
        image: phpmyadmin:5.2-apache
        environment:
            PMA_HOST: db-proxy
            PMA_USER: user_appvotaciones
            PMA_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
        networks:
            - votacion_net
        deploy:
            # phpmyadmin puede ir a cualquier nodo de app
            placement:
                constraints:
                    - node.labels.role == app
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 60s
            resources:
                reservations:
                    cpus: '0.10'
                    memory: 64M
                limits:
                    cpus: '0.5'
                    memory: 256M
            
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 256M
                limits:
                    cpus: '0.80'
                    memory: 512M

    grafana:
        image: grafana/grafana:latest
        environment:
            GF_SERVER_DOMAIN: 192.168.1.250
            GF_SERVER_ROOT_URL: http://192.168.1.250/grafana/
            GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
            # Grafana preguntará si quieres cambiarla tras el primer login
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - grafana_data:/var/lib/grafana
            - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
        networks:
            - votacion_net
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 60s
            resources:
                reservations:
                    cpus: '0.10'
                    memory: 128M
                limits:
                    cpus: '0.50'
                    memory: 256M

    node-exporter:
        image: prom/node-exporter:latest
        hostname: '{{.Node.Hostname}}'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
        networks:
            - votacion_net
        deploy:
            mode: global
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 60s
            resources:
                reservations:
                    cpus: '0.05'
                    memory: 32M # Garantiza al menos 128 MB de RAM
                limits:
                    cpus: '0.10'
                    memory: 64M

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - votacion_net
        deploy:
            mode: global
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 60s
            resources:
                reservations:
                    cpus: '0.10'
                    memory: 64M
                limits:
                    cpus: '0.20'
                    memory: 128M
            

secrets:
    db_root_password:
        external: true
    db_password:
        external: true
    galera_sync_password:
        external: true
    jwt_secret:
        external: true
    dni_pepper:
        external: true
    blockchain_secret:
        external: true

networks:
    votacion_net:
        driver: overlay # Red especial de Swarm para que los nodos se comuniquen

configs:
    esquema_sql:
        file: ./database/1_esquema_db.sql
    mock_data_sql:
        file: ./database/datos_prueba.sql

volumes:
    db_data_1:
    db_data_2:
    db_data_3:
    prometheus_data:
    grafana_data:
